// Code generated by Slice Machine. DO NOT EDIT.

import CtaSection from './CtaSection';
import Galleria from './Galleria';
import MainSections from './MainSections';

export {
	CtaSection,
	Galleria,
	MainSections,
};

export const components = {
	cta_section: CtaSection,
	content: Galleria,
	main_sections: MainSections,
};
