// Code generated by Slice Machine. DO NOT EDIT.

import CtaSection from './CtaSection';
import Galleria from './Galleria';
import MainSections from './MainSections';
import SocialLinks from './SocialLinks';

export {
	CtaSection,
	Galleria,
	MainSections,
	SocialLinks,
};

export const components = {
	cta_section: CtaSection,
	content: Galleria,
	main_sections: MainSections,
	social_links: SocialLinks,
};
