// Code generated by Slice Machine. DO NOT EDIT.

import Galleria from './Galleria';
import MainSections from './MainSections';

export {
	Galleria,
	MainSections,
};

export const components = {
	content: Galleria,
	main_sections: MainSections,
};
